spring:
  application:
    name: Kaml
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:kaml2;NON_KEYWORDS=user;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    database: H2
    show-sql: true
    generate-ddl: false
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    schemas: kaml
    create-schemas: true
    default-schema: kaml
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=user;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
server:
  port: 8089